version: '3.8'

services:
  faceit-user-service:
    build:
      context: .
      dockerfile: ./build/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_CONNECTION_URI=host=postgres port=5432 user=postgres password=postgres dbname=users sslmode=disable
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users
    ports:
      - "5432:5432"

