// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/AlecSmith96/faceit-user-service/internal/usecases (interfaces: ReadinessChecker)
//
// Generated by this command:
//
//	mockgen --build_flags=--mod=mod -destination=../../mocks/readinessChecker.go . ReadinessChecker
//
// Package mock_usecases is a generated GoMock package.
package mock_usecases

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockReadinessChecker is a mock of ReadinessChecker interface.
type MockReadinessChecker struct {
	ctrl     *gomock.Controller
	recorder *MockReadinessCheckerMockRecorder
}

// MockReadinessCheckerMockRecorder is the mock recorder for MockReadinessChecker.
type MockReadinessCheckerMockRecorder struct {
	mock *MockReadinessChecker
}

// NewMockReadinessChecker creates a new mock instance.
func NewMockReadinessChecker(ctrl *gomock.Controller) *MockReadinessChecker {
	mock := &MockReadinessChecker{ctrl: ctrl}
	mock.recorder = &MockReadinessCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReadinessChecker) EXPECT() *MockReadinessCheckerMockRecorder {
	return m.recorder
}

// CheckConnection mocks base method.
func (m *MockReadinessChecker) CheckConnection() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckConnection")
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckConnection indicates an expected call of CheckConnection.
func (mr *MockReadinessCheckerMockRecorder) CheckConnection() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckConnection", reflect.TypeOf((*MockReadinessChecker)(nil).CheckConnection))
}
